#!/bin/bash

cd
rm -rf AUTORUN-CCMINER-BANK1.2
git clone https://github.com/Boon-yalit/AUTORUN-CCMINER-BANK
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-BANK/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining
cd
cd ../bin
rm -rf add-ip edit-miner run-miner update down-grade
cd
cd AUTORUN-CCMINER-BANK
chmod +x setupdate.sh
sh setupdate.sh
